import type {
  FarmSummary,
  Detection,
  MapData,
  Report,
  Task,
  AISummary,
  YieldSummary,
  DroneStatus,
  ScanRecord,
  FarmOption,
  SvgZoneMeta,
} from './types';

export const FARM_SUMMARY: FarmSummary = {
  farm_id: 'farm-001',
  farm_name: 'สวนส้มสมชาย',
  last_scan_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  overall_health_score: 0.63,
  health_trend: 'declining',
  total_area_rai: 24.5,
  active_alerts: 4,
  zones: [
    { zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', health_score: 0.87, status: 'healthy' },
    { zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', health_score: 0.58, status: 'warning' },
    { zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', health_score: 0.31, status: 'critical' },
    { zone_id: 'zone-d', zone_name: 'แปลง 4 – ส้มสายน้ำ', health_score: 0.92, status: 'healthy' },
  ],
  top_recommendation:
    'แปลง 3 มีโรคแคงเกอร์ระบาดหนัก ควรฉีดพ่นคอปเปอร์ออกซีคลอไรด์และตัดกิ่งที่ติดโรคออกภายใน 24 ชั่วโมง',
};

export const DETECTIONS: Detection[] = [
  {
    detection_id: 'det-001',
    detected_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'Citrus Canker',
    confidence: 0.94,
    severity: 'critical',
    affected_area_pct: 38.5,
    zone_id: 'zone-c',
    zone_name: 'แปลง 3 – ส้มนาเกลือ',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.12, y: 0.18, width: 0.45, height: 0.52 },
    recommendation:
      'ฉีดพ่นคอปเปอร์ออกซีคลอไรด์ 85% WP อัตรา 30 กรัมต่อน้ำ 20 ลิตร ตัดกิ่งที่ติดโรคออกและเผาทำลายทันที',
  },
  {
    detection_id: 'det-002',
    detected_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Citrus Psyllid',
    confidence: 0.88,
    severity: 'high',
    affected_area_pct: 22.1,
    zone_id: 'zone-c',
    zone_name: 'แปลง 3 – ส้มนาเกลือ',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.3, y: 0.4, width: 0.25, height: 0.3 },
    recommendation:
      'ฉีดพ่นสารอิมิดาโคลพริด 70% WS อัตรา 5 กรัมต่อน้ำ 20 ลิตร เน้นยอดอ่อนและใบอ่อน',
  },
  {
    detection_id: 'det-003',
    detected_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'HLB Greening',
    confidence: 0.79,
    severity: 'high',
    affected_area_pct: 17.3,
    zone_id: 'zone-b',
    zone_name: 'แปลง 2 – ส้มโชกุน',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.05, y: 0.1, width: 0.6, height: 0.4 },
    recommendation:
      'กำจัดเพลี้ยไก่แจ้ส้มซึ่งเป็นพาหะ ตัดกิ่งแสดงอาการออก พิจารณาโค่นต้นที่ติดเชื้อรุนแรง',
  },
  {
    detection_id: 'det-004',
    detected_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Spider Mites',
    confidence: 0.85,
    severity: 'medium',
    affected_area_pct: 11.8,
    zone_id: 'zone-b',
    zone_name: 'แปลง 2 – ส้มโชกุน',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.2, y: 0.25, width: 0.35, height: 0.45 },
    recommendation:
      'ฉีดพ่นอะบาเมคติน 1.8% EC อัตรา 20 มล.ต่อน้ำ 20 ลิตร ในช่วงเช้าตรู่ก่อนอุณหภูมิสูง',
  },
  {
    detection_id: 'det-005',
    detected_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.97,
    severity: 'medium',
    affected_area_pct: 9.4,
    zone_id: 'zone-a',
    zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.4, y: 0.5, width: 0.3, height: 0.3 },
    recommendation:
      'ฉีดพ่นกลูโฟซิเนต 15% SL อัตรา 100 มล.ต่อน้ำ 20 ลิตร หรือกำจัดด้วยแรงงานบริเวณโคนต้น',
  },
  {
    detection_id: 'det-006',
    detected_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'Citrus Canker',
    confidence: 0.72,
    severity: 'medium',
    affected_area_pct: 8.2,
    zone_id: 'zone-b',
    zone_name: 'แปลง 2 – ส้มโชกุน',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.15, y: 0.2, width: 0.4, height: 0.35 },
    recommendation:
      'ติดตามอาการอย่างใกล้ชิด ฉีดพ่นป้องกันด้วยคอปเปอร์ออกซีคลอไรด์ ตัดใบที่แสดงอาการออก',
  },
  {
    detection_id: 'det-007',
    detected_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.91,
    severity: 'low',
    affected_area_pct: 4.7,
    zone_id: 'zone-c',
    zone_name: 'แปลง 3 – ส้มนาเกลือ',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.6, y: 0.6, width: 0.2, height: 0.25 },
    recommendation: 'กำจัดด้วยแรงงาน หรือรอจนกว่าจะรักษาโรคหลักก่อน',
  },
  {
    detection_id: 'det-008',
    detected_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Citrus Psyllid',
    confidence: 0.61,
    severity: 'low',
    affected_area_pct: 3.1,
    zone_id: 'zone-a',
    zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง',
    status: 'resolved',
    image_url: null,
    bounding_box: { x: 0.7, y: 0.3, width: 0.15, height: 0.2 },
    recommendation: 'ดำเนินการแก้ไขแล้ว ติดตามผลต่อไป',
  },
  {
    detection_id: 'det-009',
    detected_at: new Date(Date.now() - 60 * 60 * 1000 * 60).toISOString(),
    type: 'disease',
    label: 'HLB Greening',
    confidence: 0.83,
    severity: 'high',
    affected_area_pct: 19.6,
    zone_id: 'zone-c',
    zone_name: 'แปลง 3 – ส้มนาเกลือ',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.08, y: 0.35, width: 0.5, height: 0.4 },
    recommendation:
      'กำจัดเพลี้ยไก่แจ้พาหะทันที ตัดกิ่งแสดงอาการและฉีดพ่นสารทองแดงป้องกันการแพร่กระจาย',
  },
  {
    detection_id: 'det-010',
    detected_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.76,
    severity: 'medium',
    affected_area_pct: 12.3,
    zone_id: 'zone-b',
    zone_name: 'แปลง 2 – ส้มโชกุน',
    status: 'resolved',
    image_url: null,
    bounding_box: { x: 0.25, y: 0.55, width: 0.35, height: 0.28 },
    recommendation: 'ดำเนินการกำจัดวัชพืชแล้ว',
  },
  {
    detection_id: 'det-011',
    detected_at: new Date(Date.now() - 80 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Spider Mites',
    confidence: 0.69,
    severity: 'low',
    affected_area_pct: 5.8,
    zone_id: 'zone-a',
    zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.5, y: 0.2, width: 0.22, height: 0.3 },
    recommendation: 'ติดตามอาการ ถ้าพบเพิ่มให้ดำเนินการฉีดพ่นอะบาเมคตินทันที',
  },
  {
    detection_id: 'det-012',
    detected_at: new Date(Date.now() - 90 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'Citrus Canker',
    confidence: 0.92,
    severity: 'critical',
    affected_area_pct: 41.2,
    zone_id: 'zone-c',
    zone_name: 'แปลง 3 – ส้มนาเกลือ',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.1, y: 0.1, width: 0.55, height: 0.6 },
    recommendation:
      'เร่งด่วน: ฉีดพ่นคอปเปอร์ออกซีคลอไรด์ ตัดกิ่งและใบที่ติดโรคออก แยกพื้นที่เพื่อป้องกันการแพร่',
  },
  {
    detection_id: 'det-013',
    detected_at: new Date(Date.now() - 100 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.88,
    severity: 'low',
    affected_area_pct: 6.1,
    zone_id: 'zone-a',
    zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง',
    status: 'resolved',
    image_url: null,
    bounding_box: { x: 0.45, y: 0.45, width: 0.28, height: 0.32 },
    recommendation: 'กำจัดวัชพืชแล้ว',
  },
  {
    detection_id: 'det-014',
    detected_at: new Date(Date.now() - 110 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Citrus Psyllid',
    confidence: 0.75,
    severity: 'medium',
    affected_area_pct: 14.4,
    zone_id: 'zone-b',
    zone_name: 'แปลง 2 – ส้มโชกุน',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.18, y: 0.3, width: 0.4, height: 0.38 },
    recommendation:
      'ฉีดพ่นสารอิมิดาโคลพริดผสมกับน้ำสะอาด เน้นยอดอ่อนในช่วงเช้าตรู่',
  },
  {
    detection_id: 'det-015',
    detected_at: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'HLB Greening',
    confidence: 0.66,
    severity: 'medium',
    affected_area_pct: 10.7,
    zone_id: 'zone-a',
    zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง',
    status: 'resolved',
    image_url: null,
    bounding_box: { x: 0.32, y: 0.15, width: 0.38, height: 0.42 },
    recommendation: 'ดำเนินการรักษาแล้ว ตัดกิ่งที่แสดงอาการออก อาการดีขึ้น',
  },
  {
    detection_id: 'det-016',
    detected_at: new Date(Date.now() - 130 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Spider Mites',
    confidence: 0.82,
    severity: 'high',
    affected_area_pct: 25.9,
    zone_id: 'zone-c',
    zone_name: 'แปลง 3 – ส้มนาเกลือ',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.22, y: 0.28, width: 0.48, height: 0.5 },
    recommendation: 'ฉีดพ่นอะบาเมคตินและสารกำจัดไรสลับกันทุก 7 วัน เพื่อป้องกันการดื้อยา',
  },
  {
    detection_id: 'det-017',
    detected_at: new Date(Date.now() - 140 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.93,
    severity: 'low',
    affected_area_pct: 3.9,
    zone_id: 'zone-b',
    zone_name: 'แปลง 2 – ส้มโชกุน',
    status: 'resolved',
    image_url: null,
    bounding_box: { x: 0.55, y: 0.58, width: 0.2, height: 0.22 },
    recommendation: 'กำจัดด้วยแรงงานแล้ว',
  },
  {
    detection_id: 'det-018',
    detected_at: new Date(Date.now() - 150 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'Citrus Canker',
    confidence: 0.78,
    severity: 'high',
    affected_area_pct: 20.5,
    zone_id: 'zone-b',
    zone_name: 'แปลง 2 – ส้มโชกุน',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.1, y: 0.12, width: 0.5, height: 0.48 },
    recommendation:
      'ฉีดพ่นสารทองแดงและตรวจสอบรอยแผลบนผลส้มเพื่อป้องกันการสูญเสียผลผลิต',
  },
  {
    detection_id: 'det-019',
    detected_at: new Date(Date.now() - 160 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Citrus Psyllid',
    confidence: 0.84,
    severity: 'critical',
    affected_area_pct: 35.6,
    zone_id: 'zone-c',
    zone_name: 'แปลง 3 – ส้มนาเกลือ',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.05, y: 0.05, width: 0.6, height: 0.65 },
    recommendation:
      'เร่งด่วน: ระบาดหนักมาก ฉีดพ่นสารอิมิดาโคลพริดและตรวจหาอาการ HLB ในต้นที่ถูกทำลาย',
  },
  {
    detection_id: 'det-020',
    detected_at: new Date(Date.now() - 170 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.71,
    severity: 'medium',
    affected_area_pct: 13.8,
    zone_id: 'zone-a',
    zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.35, y: 0.4, width: 0.35, height: 0.35 },
    recommendation:
      'ฉีดพ่นกลูโฟซิเนตในช่วงเช้า ก่อนแสงแดดแรง ระวังสารตกค้างบนผลส้ม',
  },
];

export const MAP_DATA: MapData = {
  farm_id: 'farm-001',
  center_lat: 18.7617,
  center_lng: 98.9667,
  zoom_default: 15,
  zones: [
    {
      zone_id: 'zone-a',
      zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง',
      health_score: 0.87,
      status: 'healthy',
      polygon: [
        { lat: 18.7635, lng: 98.9645 },
        { lat: 18.7635, lng: 98.9680 },
        { lat: 18.7617, lng: 98.9680 },
        { lat: 18.7617, lng: 98.9645 },
      ],
      detection_count: 5,
    },
    {
      zone_id: 'zone-b',
      zone_name: 'แปลง 2 – ส้มโชกุน',
      health_score: 0.58,
      status: 'warning',
      polygon: [
        { lat: 18.7617, lng: 98.9645 },
        { lat: 18.7617, lng: 98.9680 },
        { lat: 18.7600, lng: 98.9680 },
        { lat: 18.7600, lng: 98.9645 },
      ],
      detection_count: 7,
    },
    {
      zone_id: 'zone-c',
      zone_name: 'แปลง 3 – ส้มนาเกลือ',
      health_score: 0.31,
      status: 'critical',
      polygon: [
        { lat: 18.7617, lng: 98.9680 },
        { lat: 18.7617, lng: 98.9710 },
        { lat: 18.7600, lng: 98.9710 },
        { lat: 18.7600, lng: 98.9680 },
      ],
      detection_count: 8,
    },
    {
      zone_id: 'zone-d',
      zone_name: 'แปลง 4 – ส้มสายน้ำ',
      health_score: 0.92,
      status: 'healthy',
      polygon: [
        { lat: 18.7635, lng: 98.9680 },
        { lat: 18.7635, lng: 98.9710 },
        { lat: 18.7617, lng: 98.9710 },
        { lat: 18.7617, lng: 98.9680 },
      ],
      detection_count: 3,
    },
  ],
  detection_markers: [
    { detection_id: 'det-001', lat: 18.7605, lng: 98.9690, type: 'disease', severity: 'critical' },
    { detection_id: 'det-002', lat: 18.7608, lng: 98.9695, type: 'pest', severity: 'high' },
    { detection_id: 'det-003', lat: 18.7610, lng: 98.9660, type: 'disease', severity: 'high' },
    { detection_id: 'det-004', lat: 18.7612, lng: 98.9658, type: 'pest', severity: 'medium' },
    { detection_id: 'det-005', lat: 18.7625, lng: 98.9662, type: 'weed', severity: 'medium' },
    { detection_id: 'det-006', lat: 18.7613, lng: 98.9655, type: 'disease', severity: 'medium' },
    { detection_id: 'det-007', lat: 18.7603, lng: 98.9698, type: 'weed', severity: 'low' },
    { detection_id: 'det-009', lat: 18.7602, lng: 98.9693, type: 'disease', severity: 'high' },
    { detection_id: 'det-012', lat: 18.7606, lng: 98.9700, type: 'disease', severity: 'critical' },
    { detection_id: 'det-014', lat: 18.7611, lng: 98.9665, type: 'pest', severity: 'medium' },
    { detection_id: 'det-016', lat: 18.7604, lng: 98.9697, type: 'pest', severity: 'high' },
    { detection_id: 'det-018', lat: 18.7609, lng: 98.9653, type: 'disease', severity: 'high' },
    { detection_id: 'det-019', lat: 18.7601, lng: 98.9702, type: 'pest', severity: 'critical' },
  ],
};

export const REPORTS: Record<'daily' | 'weekly' | 'monthly', Report> = {
  daily: {
    period: 'daily',
    generated_at: new Date().toISOString(),
    date_range: {
      from: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      to: new Date().toISOString().split('T')[0],
    },
    summary:
      'วันนี้ตรวจพบโรคแคงเกอร์และเพลี้ยไก่แจ้ส้มในแปลง 3 ระดับวิกฤติ ต้องดำเนินการแก้ไขด่วน คะแนนสุขภาพโดยรวมลดลง 0.08 จากเมื่อวาน',
    health_score_avg: 0.63,
    health_score_change: -0.08,
    total_detections: 7,
    detections_by_type: { disease: 3, weed: 1, pest: 3 },
    yield_estimate_kg: 4850,
    yield_confidence: 0.72,
    recommendations: [
      'ฉีดพ่นคอปเปอร์ออกซีคลอไรด์ในแปลง 3 ทันที',
      'ตัดกิ่งที่ติดโรคแคงเกอร์และเผาทำลาย',
      'ฉีดพ่นอิมิดาโคลพริดกำจัดเพลี้ยไก่แจ้พาหะ HLB',
    ],
    chart_data: [
      { label: '06:00', health_score: 0.71, detections: 1 },
      { label: '09:00', health_score: 0.68, detections: 2 },
      { label: '12:00', health_score: 0.65, detections: 3 },
      { label: '15:00', health_score: 0.63, detections: 5 },
      { label: '18:00', health_score: 0.63, detections: 7 },
    ],
  },
  weekly: {
    period: 'weekly',
    generated_at: new Date().toISOString(),
    date_range: {
      from: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      to: new Date().toISOString().split('T')[0],
    },
    summary:
      'สัปดาห์นี้ตรวจพบปัญหาเพิ่มขึ้น 35% จากสัปดาห์ที่แล้ว โรคแคงเกอร์แพร่ระบาดหนักในแปลง 3 ส่งผลให้คะแนนสุขภาพโดยรวมลดลงต่อเนื่อง',
    health_score_avg: 0.67,
    health_score_change: -0.15,
    total_detections: 20,
    detections_by_type: { disease: 9, weed: 6, pest: 5 },
    yield_estimate_kg: 18200,
    yield_confidence: 0.68,
    recommendations: [
      'วางแผนจัดการโรคแคงเกอร์อย่างเป็นระบบทั้งสวน',
      'พิจารณาเพิ่มความถี่การสแกนโดรนเป็น 2 ครั้งต่อวัน',
      'ปรึกษานักวิชาการเกษตรเรื่องโรค HLB ที่พบในแปลง 2',
      'ตรวจสอบดินและปรับสมดุลธาตุอาหารสำหรับส้ม',
    ],
    chart_data: [
      { label: 'จ.', health_score: 0.82, detections: 1 },
      { label: 'อ.', health_score: 0.79, detections: 2 },
      { label: 'พ.', health_score: 0.75, detections: 4 },
      { label: 'พฤ.', health_score: 0.71, detections: 5 },
      { label: 'ศ.', health_score: 0.68, detections: 6 },
      { label: 'ส.', health_score: 0.65, detections: 8 },
      { label: 'อา.', health_score: 0.63, detections: 7 },
    ],
  },
  monthly: {
    period: 'monthly',
    generated_at: new Date().toISOString(),
    date_range: {
      from: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      to: new Date().toISOString().split('T')[0],
    },
    summary:
      'เดือนนี้คะแนนสุขภาพสวนโดยรวมลดลงจาก 0.85 เหลือ 0.63 โรคแคงเกอร์และเพลี้ยไก่แจ้เป็นปัญหาหลัก ผลผลิตส้มคาดการณ์ต่ำกว่าเป้า 12%',
    health_score_avg: 0.74,
    health_score_change: -0.22,
    total_detections: 48,
    detections_by_type: { disease: 21, weed: 14, pest: 13 },
    yield_estimate_kg: 72400,
    yield_confidence: 0.61,
    recommendations: [
      'วางแผนป้องกันโรคแคงเกอร์ก่อนฤดูออกดอกครั้งหน้า',
      'ลงทุนระบบให้น้ำแบบหยดเพื่อลดความชื้นใต้ทรงพุ่ม',
      'ฝึกอบรมพนักงานเรื่องการจัดการโรค HLB และแคงเกอร์',
      'พิจารณาปลูกส้มพันธุ์ต้านทานในแปลง 3 ในรอบถัดไป',
      'สร้างแนวกันชนระหว่างแปลงเพื่อป้องกันเพลี้ยไก่แจ้แพร่',
    ],
    chart_data: [
      { label: 'สัปดาห์ 1', health_score: 0.85, detections: 4 },
      { label: 'สัปดาห์ 2', health_score: 0.80, detections: 8 },
      { label: 'สัปดาห์ 3', health_score: 0.74, detections: 14 },
      { label: 'สัปดาห์ 4', health_score: 0.63, detections: 22 },
    ],
  },
};

export const TASKS: Task[] = [
  {
    task_id: 'task-001',
    title: 'ฉีดพ่นคอปเปอร์ออกซีคลอไรด์แปลง 3',
    description: 'ใช้คอปเปอร์ออกซีคลอไรด์ 85% WP อัตรา 30 กรัมต่อน้ำ 20 ลิตร ครอบคลุมพื้นที่ทั้งหมด',
    priority: 'high',
    status: 'pending',
    due_date: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-c',
    related_detection_id: 'det-001',
  },
  {
    task_id: 'task-002',
    title: 'ฉีดพ่นอิมิดาโคลพริดกำจัดเพลี้ยไก่แจ้',
    description: 'ฉีดพ่นสารอิมิดาโคลพริด 70% WS อัตรา 5 กรัมต่อน้ำ 20 ลิตร เน้นยอดอ่อนแปลง 2 และ 3',
    priority: 'high',
    status: 'in_progress',
    due_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-b',
    related_detection_id: 'det-004',
  },
  {
    task_id: 'task-003',
    title: 'ตัดกิ่งติดโรคแคงเกอร์ออก',
    description: 'ตัดกิ่งและใบที่แสดงอาการแคงเกอร์ออก เผาทำลายทันที อย่าทิ้งไว้ในสวน',
    priority: 'high',
    status: 'pending',
    due_date: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-c',
    related_detection_id: 'det-012',
  },
  {
    task_id: 'task-004',
    title: 'กำจัดวัชพืชโคนต้นในแปลง 1',
    description: 'ฉีดพ่นกลูโฟซิเนต 15% SL อัตรา 100 มล.ต่อน้ำ 20 ลิตร บริเวณโคนต้น ระวังสารตกค้างบนผล',
    priority: 'medium',
    status: 'pending',
    due_date: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-a',
    related_detection_id: 'det-005',
  },
  {
    task_id: 'task-005',
    title: 'บินโดรนสแกนซ้ำแปลง 3',
    description: 'สแกนซ้ำหลังจากฉีดพ่นสารเคมีเพื่อประเมินการแพร่กระจายของโรคแคงเกอร์',
    priority: 'high',
    status: 'pending',
    due_date: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-c',
    related_detection_id: null,
  },
  {
    task_id: 'task-006',
    title: 'จัดซื้อสารเคมีเพิ่มเติม',
    description: 'สั่งซื้อคอปเปอร์ออกซีคลอไรด์, อิมิดาโคลพริด, และอะบาเมคติน 1.8% EC',
    priority: 'medium',
    status: 'in_progress',
    due_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: null,
    related_detection_id: null,
  },
  {
    task_id: 'task-007',
    title: 'รายงานโรค HLB ให้เกษตรอำเภอ',
    description: 'แจ้งเจ้าหน้าที่เกษตรอำเภอเรื่องโรค HLB Greening ในสวนส้ม เพื่อขอคำแนะนำและความช่วยเหลือ',
    priority: 'low',
    status: 'pending',
    due_date: new Date(Date.now() + 96 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: null,
    related_detection_id: null,
  },
  {
    task_id: 'task-008',
    title: 'ติดตั้งระบบน้ำหยดแปลง 2',
    description: 'ติดตั้งระบบให้น้ำแบบหยดในแปลง 2 เพื่อลดความชื้นใต้ทรงพุ่มและลดโรคเชื้อรา',
    priority: 'low',
    status: 'done',
    due_date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-b',
    related_detection_id: null,
  },
  {
    task_id: 'task-009',
    title: 'ฉีดพ่นอะบาเมคตินกำจัดไรแดง',
    description: 'ฉีดพ่นอะบาเมคติน 1.8% EC อัตรา 20 มล.ต่อน้ำ 20 ลิตร ครอบคลุมแปลง 2 ในช่วงเช้าตรู่',
    priority: 'high',
    status: 'pending',
    due_date: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-b',
    related_detection_id: 'det-004',
  },
  {
    task_id: 'task-010',
    title: 'บันทึกข้อมูลสภาพอากาศ',
    description: 'จดบันทึกอุณหภูมิ ความชื้น และปริมาณน้ำฝนประจำวัน เพื่อวิเคราะห์ความเสี่ยงโรค',
    priority: 'low',
    status: 'done',
    due_date: new Date().toISOString().split('T')[0],
    zone_id: null,
    related_detection_id: null,
  },
];

export const YIELD_SUMMARY: YieldSummary = {
  estimated_kg: 9250,
  quality_grade: 'B',
  harvest_readiness_pct: 72,
  confidence: 0.78,
  zone_yields: [
    { zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', yield_level: 'high', estimated_kg: 4800 },
    { zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', yield_level: 'medium', estimated_kg: 3200 },
    { zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', yield_level: 'low', estimated_kg: 1250 },
  ],
  plant_count: 12450,
  trend_pct: 12,
  days_since_planting: 87,
  estimated_harvest_date: '2026-06-15',
  growth_stage: 'near_harvest',
  grade_breakdown: { A: 38, B: 41, C: 16, damaged: 5 },
  trend_data: [
    { label: '7 วัน', kg: 8100 },
    { label: '6 วัน', kg: 8350 },
    { label: '5 วัน', kg: 8290 },
    { label: '4 วัน', kg: 8600 },
    { label: '3 วัน', kg: 8820 },
    { label: '2 วัน', kg: 9100 },
    { label: 'วันนี้', kg: 9250 },
  ],
  market_value_thb: 231250,
  ai_insights: [
    'แปลง 2 มีการติดผลน้อยกว่าปกติ ควรเพิ่มปุ๋ยโพแทสเซียมและแคลเซียมเพื่อกระตุ้น',
    'แปลง 3 เสี่ยงสูญเสียผลผลิตจากโรคแคงเกอร์ ต้องควบคุมด่วน',
    'คาดการณ์เก็บเกี่ยวส้มสายน้ำผึ้งภายใน 29 วัน เตรียมตะกร้าและรถขนส่ง',
    'ราคาส้มสายน้ำผึ้งอยู่ที่ 25 บาท/กก. เหมาะสำหรับตลาดพรีเมียม',
  ],
};

export const YIELD_SUMMARY_WEEKLY: YieldSummary = {
  estimated_kg: 63800,
  quality_grade: 'B',
  harvest_readiness_pct: 72,
  confidence: 0.76,
  zone_yields: [
    { zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', yield_level: 'high', estimated_kg: 33400 },
    { zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', yield_level: 'medium', estimated_kg: 21700 },
    { zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', yield_level: 'low', estimated_kg: 8700 },
  ],
  plant_count: 12450,
  trend_pct: 8,
  days_since_planting: 87,
  estimated_harvest_date: '2026-06-15',
  growth_stage: 'near_harvest',
  grade_breakdown: { A: 35, B: 43, C: 17, damaged: 5 },
  trend_data: [
    { label: 'สป.5', kg: 55200 },
    { label: 'สป.6', kg: 57100 },
    { label: 'สป.7', kg: 58900 },
    { label: 'สป.8', kg: 63800 },
  ],
  market_value_thb: 1595000,
  ai_insights: [
    'ผลผลิตส้มรวมรายสัปดาห์เพิ่มขึ้น 8% ต่อเนื่องเป็นสัปดาห์ที่ 3',
    'แปลง 3 ยังคงส่งผลต่อคุณภาพรวม ควรเร่งดำเนินการรักษาโรคแคงเกอร์',
    'คาดการณ์เก็บเกี่ยวส้มสายน้ำผึ้งยังอยู่ในกำหนด ไม่มีการเลื่อน',
    'ราคาส้มโชกุนในตลาดเพิ่มขึ้น 5% ส่งผลดีต่อมูลค่ารายสัปดาห์',
  ],
};

export const YIELD_SUMMARY_MONTHLY: YieldSummary = {
  estimated_kg: 251000,
  quality_grade: 'B',
  harvest_readiness_pct: 72,
  confidence: 0.69,
  zone_yields: [
    { zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', yield_level: 'high', estimated_kg: 131500 },
    { zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', yield_level: 'medium', estimated_kg: 84300 },
    { zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', yield_level: 'low', estimated_kg: 35200 },
  ],
  plant_count: 12450,
  trend_pct: -3,
  days_since_planting: 87,
  estimated_harvest_date: '2026-06-15',
  growth_stage: 'near_harvest',
  grade_breakdown: { A: 32, B: 44, C: 18, damaged: 6 },
  trend_data: [
    { label: 'ม.ค.', kg: 261000 },
    { label: 'ก.พ.', kg: 258000 },
    { label: 'มี.ค.', kg: 255000 },
    { label: 'เม.ย.', kg: 254000 },
    { label: 'พ.ค.', kg: 251000 },
  ],
  market_value_thb: 6275000,
  ai_insights: [
    'ผลผลิตส้มรายเดือนลดลง 3% เนื่องจากการระบาดของโรคแคงเกอร์ในแปลง 3',
    'หากควบคุมโรคได้ภายใน 2 สัปดาห์ คาดผลผลิตจะฟื้นตัวในเดือนหน้า',
    'มูลค่าตลาดส้มรวมเดือนนี้สูงกว่าปีที่แล้ว 18% จากราคาส้มที่เพิ่มขึ้น',
    'วางแผนรอบหน้าโดยขยายพื้นที่แปลง 1 และ 4 ที่มีสุขภาพดี',
  ],
};

export const DRONE_STATUS: DroneStatus = {
  mission_id: 'mission-042',
  status: 'uploading',
  completed_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  coverage_pct: 94,
  battery_pct: 68,
  signal_strength: 'strong',
  upload_pct: 67,
  last_scan_area_rai: 23.1,
};

export const FARM_LIST: FarmOption[] = [
  {
    farm_id: 'farm-001',
    farm_name: 'สวนส้มสมชาย',
    total_area_rai: 24.5,
    zones: [
      { zone_id: 'zone-a', zone_name: 'แปลง 1', area_rai: 10.5, crop: 'ส้มสายน้ำผึ้ง' },
      { zone_id: 'zone-b', zone_name: 'แปลง 2', area_rai: 8.0, crop: 'ส้มโชกุน' },
      { zone_id: 'zone-c', zone_name: 'แปลง 3', area_rai: 6.0, crop: 'ส้มนาเกลือ' },
      { zone_id: 'zone-d', zone_name: 'แปลง 4', area_rai: 8.0, crop: 'ส้มสายน้ำ' },
    ],
  },
  {
    farm_id: 'farm-002',
    farm_name: 'สวนส้มสมหมาย',
    total_area_rai: 18.0,
    zones: [
      { zone_id: 'zone-d', zone_name: 'แปลง 1', area_rai: 10.0, crop: 'ส้มสายน้ำผึ้ง' },
      { zone_id: 'zone-e', zone_name: 'แปลง 2', area_rai: 8.0, crop: 'ส้มโชกุน' },
    ],
  },
  {
    farm_id: 'farm-003',
    farm_name: 'สวนส้มบุญมาก',
    total_area_rai: 32.0,
    zones: [
      { zone_id: 'zone-f', zone_name: 'แปลง 1', area_rai: 8.0, crop: 'ส้มสายน้ำ' },
      { zone_id: 'zone-g', zone_name: 'แปลง 2', area_rai: 9.0, crop: 'ส้มนาเกลือ' },
      { zone_id: 'zone-h', zone_name: 'แปลง 3', area_rai: 8.0, crop: 'ส้มสายน้ำผึ้ง' },
      { zone_id: 'zone-i', zone_name: 'แปลง 4', area_rai: 7.0, crop: 'ส้มโชกุน' },
    ],
  },
];

export const SCAN_HISTORY: ScanRecord[] = [
  { scan_id: 'scan-001', scanned_at: new Date().toISOString(), label: 'ผลล่าสุด' },
  {
    scan_id: 'scan-002',
    scanned_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    label: 'เมื่อวาน',
  },
  {
    scan_id: 'scan-003',
    scanned_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    label: '3 วันที่แล้ว',
  },
  {
    scan_id: 'scan-004',
    scanned_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    label: '7 วันที่แล้ว',
  },
];

// ── Per-scan historical snapshots ─────────────────────────────
// Story: farm was healthy 7 days ago, steadily declining to today's critical state.

const FARM_SUMMARY_D1: FarmSummary = {
  ...FARM_SUMMARY,
  last_scan_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  overall_health_score: 0.71,
  health_trend: 'declining',
  active_alerts: 3,
  zones: [
    { zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', health_score: 0.88, status: 'healthy' },
    { zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', health_score: 0.64, status: 'warning' },
    { zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', health_score: 0.38, status: 'critical' },
  ],
  top_recommendation: 'แปลง 3 เริ่มมีโรคแคงเกอร์ระบาด ควรเตรียมฉีดพ่นคอปเปอร์ออกซีคลอไรด์ทันที',
};

const FARM_SUMMARY_D3: FarmSummary = {
  ...FARM_SUMMARY,
  last_scan_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  overall_health_score: 0.75,
  health_trend: 'stable',
  active_alerts: 2,
  zones: [
    { zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', health_score: 0.90, status: 'healthy' },
    { zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', health_score: 0.71, status: 'warning' },
    { zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', health_score: 0.48, status: 'warning' },
  ],
  top_recommendation: 'แปลง 3 มีสัญญาณวัชพืชและเริ่มพบไรแดง ควรดำเนินการกำจัดก่อนแพร่ระบาด',
};

const FARM_SUMMARY_D7: FarmSummary = {
  ...FARM_SUMMARY,
  last_scan_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  overall_health_score: 0.85,
  health_trend: 'improving',
  active_alerts: 1,
  zones: [
    { zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', health_score: 0.93, status: 'healthy' },
    { zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', health_score: 0.82, status: 'healthy' },
    { zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', health_score: 0.68, status: 'warning' },
  ],
  top_recommendation: 'สวนส้มโดยรวมมีสุขภาพดี ควรดูแลความชื้นใต้ทรงพุ่มในแปลง 3 เพื่อป้องกันวัชพืช',
};

const DETECTIONS_D1: Detection[] = [
  { detection_id: 'det-d1-001', detected_at: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(), type: 'disease', label: 'Citrus Canker', confidence: 0.91, severity: 'high', affected_area_pct: 28.2, zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', status: 'active', image_url: null, bounding_box: { x: 0.12, y: 0.18, width: 0.45, height: 0.52 }, recommendation: 'ฉีดพ่นคอปเปอร์ออกซีคลอไรด์ 85% WP ทันที และตัดกิ่งติดโรคออก' },
  { detection_id: 'det-d1-002', detected_at: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(), type: 'pest', label: 'Citrus Psyllid', confidence: 0.84, severity: 'high', affected_area_pct: 18.5, zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', status: 'active', image_url: null, bounding_box: { x: 0.3, y: 0.4, width: 0.25, height: 0.3 }, recommendation: 'ฉีดพ่นสารอิมิดาโคลพริด 70% WS เน้นยอดอ่อนและใบอ่อน' },
  { detection_id: 'det-d1-003', detected_at: new Date(Date.now() - 29 * 60 * 60 * 1000).toISOString(), type: 'disease', label: 'HLB Greening', confidence: 0.76, severity: 'medium', affected_area_pct: 13.1, zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', status: 'active', image_url: null, bounding_box: { x: 0.05, y: 0.1, width: 0.6, height: 0.4 }, recommendation: 'กำจัดเพลี้ยไก่แจ้พาหะ ตัดกิ่งแสดงอาการออก' },
  { detection_id: 'det-d1-004', detected_at: new Date(Date.now() - 32 * 60 * 60 * 1000).toISOString(), type: 'pest', label: 'Spider Mites', confidence: 0.80, severity: 'medium', affected_area_pct: 9.2, zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', status: 'active', image_url: null, bounding_box: { x: 0.2, y: 0.25, width: 0.35, height: 0.45 }, recommendation: 'ฉีดพ่นอะบาเมคติน 1.8% EC ในช่วงเช้าตรู่' },
  { detection_id: 'det-d1-005', detected_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(), type: 'weed', label: 'Broadleaf Weeds', confidence: 0.95, severity: 'medium', affected_area_pct: 8.1, zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', status: 'active', image_url: null, bounding_box: { x: 0.4, y: 0.5, width: 0.3, height: 0.3 }, recommendation: 'ฉีดพ่นกลูโฟซิเนต 15% SL บริเวณโคนต้น' },
  { detection_id: 'det-d1-006', detected_at: new Date(Date.now() - 44 * 60 * 60 * 1000).toISOString(), type: 'disease', label: 'Citrus Canker', confidence: 0.70, severity: 'medium', affected_area_pct: 7.5, zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', status: 'active', image_url: null, bounding_box: { x: 0.15, y: 0.2, width: 0.4, height: 0.35 }, recommendation: 'ติดตามอาการอย่างใกล้ชิด ฉีดพ่นป้องกันด้วยสารทองแดง' },
];

const DETECTIONS_D3: Detection[] = [
  { detection_id: 'det-d3-001', detected_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), type: 'disease', label: 'Citrus Canker', confidence: 0.82, severity: 'medium', affected_area_pct: 14.3, zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', status: 'active', image_url: null, bounding_box: { x: 0.12, y: 0.18, width: 0.35, height: 0.42 }, recommendation: 'เฝ้าระวัง พิจารณาฉีดพ่นคอปเปอร์ออกซีคลอไรด์ป้องกัน' },
  { detection_id: 'det-d3-002', detected_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 4 * 60 * 60 * 1000).toISOString(), type: 'pest', label: 'Spider Mites', confidence: 0.73, severity: 'medium', affected_area_pct: 8.7, zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', status: 'active', image_url: null, bounding_box: { x: 0.2, y: 0.25, width: 0.35, height: 0.45 }, recommendation: 'ฉีดพ่นอะบาเมคตินเพื่อลดประชากรไรแดง' },
  { detection_id: 'det-d3-003', detected_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 8 * 60 * 60 * 1000).toISOString(), type: 'weed', label: 'Broadleaf Weeds', confidence: 0.90, severity: 'low', affected_area_pct: 6.2, zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', status: 'active', image_url: null, bounding_box: { x: 0.4, y: 0.5, width: 0.3, height: 0.3 }, recommendation: 'กำจัดวัชพืชด้วยแรงงาน หรือรอให้เหมาะสม' },
  { detection_id: 'det-d3-004', detected_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 12 * 60 * 60 * 1000).toISOString(), type: 'weed', label: 'Broadleaf Weeds', confidence: 0.85, severity: 'low', affected_area_pct: 4.1, zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', status: 'active', image_url: null, bounding_box: { x: 0.55, y: 0.58, width: 0.2, height: 0.22 }, recommendation: 'กำจัดวัชพืชด้วยแรงงาน' },
];

const DETECTIONS_D7: Detection[] = [
  { detection_id: 'det-d7-001', detected_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), type: 'weed', label: 'Broadleaf Weeds', confidence: 0.88, severity: 'low', affected_area_pct: 5.3, zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', status: 'active', image_url: null, bounding_box: { x: 0.45, y: 0.45, width: 0.28, height: 0.32 }, recommendation: 'ติดตามอาการ ยังไม่จำเป็นต้องดำเนินการทันที' },
  { detection_id: 'det-d7-002', detected_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 - 3 * 60 * 60 * 1000).toISOString(), type: 'pest', label: 'Spider Mites', confidence: 0.65, severity: 'low', affected_area_pct: 3.1, zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', status: 'active', image_url: null, bounding_box: { x: 0.7, y: 0.3, width: 0.15, height: 0.2 }, recommendation: 'ติดตามอาการไรแดง ประชากรยังน้อย' },
];

const YIELD_D1: YieldSummary = {
  estimated_kg: 8900,
  quality_grade: 'B',
  harvest_readiness_pct: 69,
  confidence: 0.81,
  zone_yields: [
    { zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', yield_level: 'high', estimated_kg: 4650 },
    { zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', yield_level: 'medium', estimated_kg: 3050 },
    { zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', yield_level: 'low', estimated_kg: 1200 },
  ],
  plant_count: 12450,
  trend_pct: 9,
  days_since_planting: 86,
  estimated_harvest_date: '2026-06-15',
  growth_stage: 'near_harvest',
  grade_breakdown: { A: 39, B: 41, C: 15, damaged: 5 },
  trend_data: [
    { label: '7 วัน', kg: 7900 }, { label: '6 วัน', kg: 8100 }, { label: '5 วัน', kg: 8050 },
    { label: '4 วัน', kg: 8300 }, { label: '3 วัน', kg: 8500 }, { label: '2 วัน', kg: 8750 },
    { label: 'เมื่อวาน', kg: 8900 },
  ],
  market_value_thb: 222500,
  ai_insights: [
    'ผลผลิตส้มยังเพิ่มขึ้นแต่ชะลอตัว เนื่องจากสภาพโรคแคงเกอร์ในแปลง 3',
    'ควรเร่งดำเนินการรักษาโรคเพื่อรักษาระดับผลผลิต',
    'คาดการณ์เก็บเกี่ยวส้มสายน้ำผึ้งภายใน 30 วัน เตรียมอุปกรณ์ล่วงหน้า',
    'คุณภาพส้มระดับ B เป็นที่ต้องการของตลาด ราคา 25 บาท/กก.',
  ],
};

const YIELD_D3: YieldSummary = {
  estimated_kg: 8400,
  quality_grade: 'B',
  harvest_readiness_pct: 65,
  confidence: 0.83,
  zone_yields: [
    { zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', yield_level: 'high', estimated_kg: 4400 },
    { zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', yield_level: 'medium', estimated_kg: 2900 },
    { zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', yield_level: 'medium', estimated_kg: 1100 },
  ],
  plant_count: 12450,
  trend_pct: 7,
  days_since_planting: 84,
  estimated_harvest_date: '2026-06-15',
  growth_stage: 'near_harvest',
  grade_breakdown: { A: 41, B: 40, C: 14, damaged: 5 },
  trend_data: [
    { label: '7 วัน', kg: 7500 }, { label: '6 วัน', kg: 7650 }, { label: '5 วัน', kg: 7800 },
    { label: '4 วัน', kg: 7950 }, { label: '3 วัน', kg: 8100 }, { label: '2 วัน', kg: 8250 },
    { label: '3 วันที่แล้ว', kg: 8400 },
  ],
  market_value_thb: 210000,
  ai_insights: [
    'ผลผลิตส้มเพิ่มขึ้นสม่ำเสมอ 7% ต่อสัปดาห์',
    'แปลง 3 เริ่มส่งสัญญาณชะลอตัว ควรเฝ้าระวังไรแดง',
    'คาดการณ์เก็บเกี่ยวส้มภายใน 32 วัน',
    'แนะนำใส่ปุ๋ยโพแทสเซียมและแคลเซียมเพื่อเพิ่มคุณภาพผลส้ม',
  ],
};

const YIELD_D7: YieldSummary = {
  estimated_kg: 7800,
  quality_grade: 'A',
  harvest_readiness_pct: 58,
  confidence: 0.88,
  zone_yields: [
    { zone_id: 'zone-a', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', yield_level: 'high', estimated_kg: 4100 },
    { zone_id: 'zone-b', zone_name: 'แปลง 2 – ส้มโชกุน', yield_level: 'high', estimated_kg: 2700 },
    { zone_id: 'zone-c', zone_name: 'แปลง 3 – ส้มนาเกลือ', yield_level: 'medium', estimated_kg: 1000 },
  ],
  plant_count: 12450,
  trend_pct: 15,
  days_since_planting: 80,
  estimated_harvest_date: '2026-06-15',
  growth_stage: 'near_harvest',
  grade_breakdown: { A: 45, B: 38, C: 13, damaged: 4 },
  trend_data: [
    { label: '7 วัน', kg: 6800 }, { label: '6 วัน', kg: 6950 }, { label: '5 วัน', kg: 7100 },
    { label: '4 วัน', kg: 7300 }, { label: '3 วัน', kg: 7500 }, { label: '2 วัน', kg: 7650 },
    { label: '7 วันที่แล้ว', kg: 7800 },
  ],
  market_value_thb: 195000,
  ai_insights: [
    'สวนส้มมีสุขภาพดีมาก ผลผลิตเพิ่มขึ้น 15% ต่อเนื่อง',
    'คุณภาพเกรด A สูงสุดในรอบเดือน เหมาะสำหรับตลาดพรีเมียม',
    'คาดการณ์เก็บเกี่ยวส้มสายน้ำผึ้งภายใน 36 วัน สภาพสมบูรณ์ดีมาก',
    'ทุกแปลงเติบโตตามแผน ไม่มีโรคหรือแมลงที่น่ากังวล',
  ],
};

export interface ScanSnapshot {
  farm: FarmSummary;
  detections: Detection[];
  yield_: YieldSummary;
}

export const SCAN_SNAPSHOTS: Record<string, ScanSnapshot> = {
  'scan-001': { farm: FARM_SUMMARY, detections: DETECTIONS, yield_: YIELD_SUMMARY },
  'scan-002': { farm: FARM_SUMMARY_D1, detections: DETECTIONS_D1, yield_: YIELD_D1 },
  'scan-003': { farm: FARM_SUMMARY_D3, detections: DETECTIONS_D3, yield_: YIELD_D3 },
  'scan-004': { farm: FARM_SUMMARY_D7, detections: DETECTIONS_D7, yield_: YIELD_D7 },
};

// ── Per-farm snapshots ─────────────────────────────────────────
// Story: สวนส้มสมหมาย is healthy, สวนส้มบุญมาก has severe multi-zone problems.

const FARM_SUMMARY_002: FarmSummary = {
  farm_id: 'farm-002',
  farm_name: 'สวนส้มสมหมาย',
  last_scan_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
  overall_health_score: 0.79,
  health_trend: 'stable',
  total_area_rai: 18.0,
  active_alerts: 1,
  zones: [
    { zone_id: 'zone-d', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', health_score: 0.87, status: 'healthy' },
    { zone_id: 'zone-e', zone_name: 'แปลง 2 – ส้มโชกุน', health_score: 0.68, status: 'warning' },
  ],
  top_recommendation: 'แปลง 2 มีวัชพืชเริ่มระบาด ควรฉีดพ่นกลูโฟซิเนตบริเวณโคนต้นส้มในสัปดาห์นี้',
};

const DETECTIONS_002: Detection[] = [
  { detection_id: 'det-002-001', detected_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), type: 'pest', label: 'Spider Mites', confidence: 0.81, severity: 'medium', affected_area_pct: 11.2, zone_id: 'zone-e', zone_name: 'แปลง 2 – ส้มโชกุน', status: 'active', image_url: null, bounding_box: { x: 0.2, y: 0.25, width: 0.35, height: 0.45 }, recommendation: 'ฉีดพ่นอะบาเมคติน 1.8% EC ในช่วงเช้าตรู่ก่อนแดดแรง' },
  { detection_id: 'det-002-002', detected_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), type: 'weed', label: 'Broadleaf Weeds', confidence: 0.93, severity: 'medium', affected_area_pct: 8.7, zone_id: 'zone-e', zone_name: 'แปลง 2 – ส้มโชกุน', status: 'active', image_url: null, bounding_box: { x: 0.4, y: 0.5, width: 0.3, height: 0.3 }, recommendation: 'ฉีดพ่นกลูโฟซิเนน 15% SL บริเวณโคนต้น ระวังสารตกค้างบนผล' },
  { detection_id: 'det-002-003', detected_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(), type: 'weed', label: 'Broadleaf Weeds', confidence: 0.85, severity: 'low', affected_area_pct: 4.3, zone_id: 'zone-d', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', status: 'active', image_url: null, bounding_box: { x: 0.55, y: 0.45, width: 0.25, height: 0.28 }, recommendation: 'ติดตามอาการ กำจัดด้วยแรงงานได้' },
];

const YIELD_SUMMARY_002: YieldSummary = {
  estimated_kg: 6200,
  quality_grade: 'A',
  harvest_readiness_pct: 81,
  confidence: 0.85,
  zone_yields: [
    { zone_id: 'zone-d', zone_name: 'แปลง 1 – ส้มสายน้ำผึ้ง', yield_level: 'high', estimated_kg: 3700 },
    { zone_id: 'zone-e', zone_name: 'แปลง 2 – ส้มโชกุน', yield_level: 'medium', estimated_kg: 2500 },
  ],
  plant_count: 8100,
  trend_pct: 11,
  days_since_planting: 92,
  estimated_harvest_date: '2026-06-08',
  growth_stage: 'near_harvest',
  grade_breakdown: { A: 52, B: 35, C: 10, damaged: 3 },
  trend_data: [
    { label: '7 วัน', kg: 5500 }, { label: '6 วัน', kg: 5650 }, { label: '5 วัน', kg: 5780 },
    { label: '4 วัน', kg: 5900 }, { label: '3 วัน', kg: 6000 }, { label: '2 วัน', kg: 6100 },
    { label: 'วันนี้', kg: 6200 },
  ],
  market_value_thb: 155000,
  ai_insights: [
    'สวนส้มมีสุขภาพดี คุณภาพเกรด A สม่ำเสมอ',
    'แปลง 1 ผลผลิตส้มสายน้ำผึ้งสูง เหมาะสำหรับตลาดส่งออกพรีเมียม',
    'คาดการณ์เก็บเกี่ยวส้มใน 20 วัน เร็วกว่าสวนอื่นในพื้นที่',
    'แนะนำขยายพื้นที่แปลง 1 ในฤดูหน้าเพื่อเพิ่มผลผลิต',
  ],
};

const FARM_SUMMARY_003: FarmSummary = {
  farm_id: 'farm-003',
  farm_name: 'สวนส้มบุญมาก',
  last_scan_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  overall_health_score: 0.52,
  health_trend: 'declining',
  total_area_rai: 32.0,
  active_alerts: 5,
  zones: [
    { zone_id: 'zone-f', zone_name: 'แปลง 1 – ส้มสายน้ำ', health_score: 0.74, status: 'warning' },
    { zone_id: 'zone-g', zone_name: 'แปลง 2 – ส้มนาเกลือ', health_score: 0.43, status: 'critical' },
    { zone_id: 'zone-h', zone_name: 'แปลง 3 – ส้มสายน้ำผึ้ง', health_score: 0.82, status: 'healthy' },
    { zone_id: 'zone-i', zone_name: 'แปลง 4 – ส้มโชกุน', health_score: 0.35, status: 'critical' },
  ],
  top_recommendation: 'แปลง 2 และ 4 มีโรคแคงเกอร์และแมลงระบาดหนัก ต้องเร่งดำเนินการแก้ไขทันที',
};

const DETECTIONS_003: Detection[] = [
  { detection_id: 'det-003-001', detected_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), type: 'disease', label: 'Citrus Canker', confidence: 0.95, severity: 'critical', affected_area_pct: 44.1, zone_id: 'zone-g', zone_name: 'แปลง 2 – ส้มนาเกลือ', status: 'active', image_url: null, bounding_box: { x: 0.1, y: 0.1, width: 0.55, height: 0.6 }, recommendation: 'เร่งด่วน: ฉีดพ่นคอปเปอร์ออกซีคลอไรด์ทันที ตัดกิ่งติดโรคออกและเผาทำลาย' },
  { detection_id: 'det-003-002', detected_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), type: 'pest', label: 'Citrus Psyllid', confidence: 0.89, severity: 'critical', affected_area_pct: 39.7, zone_id: 'zone-i', zone_name: 'แปลง 4 – ส้มโชกุน', status: 'active', image_url: null, bounding_box: { x: 0.05, y: 0.05, width: 0.6, height: 0.65 }, recommendation: 'เร่งด่วน: ระบาดหนักมาก ฉีดพ่นอิมิดาโคลพริดและตรวจหาอาการ HLB ทันที' },
  { detection_id: 'det-003-003', detected_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), type: 'disease', label: 'HLB Greening', confidence: 0.82, severity: 'high', affected_area_pct: 22.3, zone_id: 'zone-i', zone_name: 'แปลง 4 – ส้มโชกุน', status: 'active', image_url: null, bounding_box: { x: 0.08, y: 0.35, width: 0.5, height: 0.4 }, recommendation: 'กำจัดเพลี้ยไก่แจ้พาหะทันที พิจารณาโค่นต้นที่ติดเชื้อรุนแรง' },
  { detection_id: 'det-003-004', detected_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(), type: 'pest', label: 'Spider Mites', confidence: 0.77, severity: 'high', affected_area_pct: 19.8, zone_id: 'zone-g', zone_name: 'แปลง 2 – ส้มนาเกลือ', status: 'active', image_url: null, bounding_box: { x: 0.22, y: 0.28, width: 0.48, height: 0.5 }, recommendation: 'ฉีดพ่นอะบาเมคตินสลับกับสารกำจัดไรทุก 7 วัน ป้องกันการดื้อยา' },
  { detection_id: 'det-003-005', detected_at: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(), type: 'weed', label: 'Broadleaf Weeds', confidence: 0.91, severity: 'medium', affected_area_pct: 15.2, zone_id: 'zone-f', zone_name: 'แปลง 1 – ส้มสายน้ำ', status: 'active', image_url: null, bounding_box: { x: 0.35, y: 0.4, width: 0.35, height: 0.35 }, recommendation: 'ฉีดพ่นกลูโฟซิเนตในช่วงเช้าก่อนแสงแดดแรง' },
  { detection_id: 'det-003-006', detected_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), type: 'disease', label: 'Citrus Canker', confidence: 0.74, severity: 'medium', affected_area_pct: 12.1, zone_id: 'zone-f', zone_name: 'แปลง 1 – ส้มสายน้ำ', status: 'active', image_url: null, bounding_box: { x: 0.15, y: 0.2, width: 0.4, height: 0.35 }, recommendation: 'ติดตามอาการ เฝ้าระวังการแพร่จากแปลง 2' },
  { detection_id: 'det-003-007', detected_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(), type: 'weed', label: 'Broadleaf Weeds', confidence: 0.87, severity: 'low', affected_area_pct: 5.4, zone_id: 'zone-h', zone_name: 'แปลง 3 – ส้มสายน้ำผึ้ง', status: 'active', image_url: null, bounding_box: { x: 0.45, y: 0.45, width: 0.28, height: 0.32 }, recommendation: 'กำจัดวัชพืชด้วยแรงงาน' },
];

const YIELD_SUMMARY_003: YieldSummary = {
  estimated_kg: 11800,
  quality_grade: 'C',
  harvest_readiness_pct: 55,
  confidence: 0.71,
  zone_yields: [
    { zone_id: 'zone-f', zone_name: 'แปลง 1 – ส้มสายน้ำ', yield_level: 'medium', estimated_kg: 3400 },
    { zone_id: 'zone-g', zone_name: 'แปลง 2 – ส้มนาเกลือ', yield_level: 'low', estimated_kg: 2100 },
    { zone_id: 'zone-h', zone_name: 'แปลง 3 – ส้มสายน้ำผึ้ง', yield_level: 'high', estimated_kg: 4400 },
    { zone_id: 'zone-i', zone_name: 'แปลง 4 – ส้มโชกุน', yield_level: 'low', estimated_kg: 1900 },
  ],
  plant_count: 17600,
  trend_pct: -8,
  days_since_planting: 94,
  estimated_harvest_date: '2026-06-20',
  growth_stage: 'near_harvest',
  grade_breakdown: { A: 22, B: 38, C: 28, damaged: 12 },
  trend_data: [
    { label: '7 วัน', kg: 13100 }, { label: '6 วัน', kg: 12900 }, { label: '5 วัน', kg: 12600 },
    { label: '4 วัน', kg: 12400 }, { label: '3 วัน', kg: 12100 }, { label: '2 วัน', kg: 11950 },
    { label: 'วันนี้', kg: 11800 },
  ],
  market_value_thb: 295000,
  ai_insights: [
    'แปลง 2 และ 4 มีผลผลิตส้มลดลงมากจากการระบาดของโรคแคงเกอร์และเพลี้ยไก่แจ้',
    'แปลง 3 มีสุขภาพดีเป็นความหวังหลักของฤดูกาลนี้',
    'หากไม่ควบคุมโรคได้ภายใน 1 สัปดาห์ คาดผลผลิตจะลดลงอีก 15-20%',
    'แนะนำปลูกส้มพันธุ์ต้านทาน HLB ในแปลง 2 และ 4 ในฤดูหน้า',
  ],
};

export const FARM_SNAPSHOTS: Record<string, ScanSnapshot> = {
  'farm-001': SCAN_SNAPSHOTS['scan-001'],
  'farm-002': { farm: FARM_SUMMARY_002, detections: DETECTIONS_002, yield_: YIELD_SUMMARY_002 },
  'farm-003': { farm: FARM_SUMMARY_003, detections: DETECTIONS_003, yield_: YIELD_SUMMARY_003 },
};

// ── SVG Farm Map zone definitions ────────────────────────────────
// One entry per visual quadrant; zone_id aligns with FARM_SUMMARY zones.
export const SVG_ZONES: SvgZoneMeta[] = [
  {
    zone_id: 'zone-a',
    label: 'แปลง 1',
    label_th: 'NW · ส้มสายน้ำผึ้ง',
    quadrant: 'NW',
    stage: 'mature',
    stage_th: 'Mature · ผลสุกพร้อมเก็บ',
    stage_color: '#2D6A4F',
    density: 56,
    tree_count: 312,
    grades: { A: 55, B: 25, C: 12, U: 8 },
    problems: { insect: 8, disease: 5, weed: 2 },
    harvest: 'not',
    health_score: 0.87,
    svg_rect: { x: 4, y: 4, w: 254, h: 200 },
  },
  {
    zone_id: 'zone-b',
    label: 'แปลง 2',
    label_th: 'NE · ส้มโชกุน',
    quadrant: 'NE',
    stage: 'growing',
    stage_th: 'Growing · ผลกำลังโต',
    stage_color: '#4A8A60',
    density: 48,
    tree_count: 287,
    grades: { A: 30, B: 40, C: 20, U: 10 },
    problems: { insect: 4, disease: 3, weed: 11 },
    harvest: 'soon',
    health_score: 0.58,
    svg_rect: { x: 302, y: 4, w: 254, h: 200 },
  },
  {
    zone_id: 'zone-c',
    label: 'แปลง 3',
    label_th: 'SW · ส้มนาเกลือ',
    quadrant: 'SW',
    stage: 'near_harvest',
    stage_th: 'Near Harvest · ใกล้เก็บเกี่ยว',
    stage_color: '#B8860B',
    density: 38,
    tree_count: 198,
    grades: { A: 10, B: 20, C: 35, U: 35 },
    problems: { insect: 2, disease: 7, weed: 6 },
    harvest: 'not',
    health_score: 0.31,
    svg_rect: { x: 4, y: 244, w: 254, h: 192 },
  },
  {
    zone_id: 'zone-d',
    label: 'แปลง 4',
    label_th: 'SE · ส้มสายน้ำ',
    quadrant: 'SE',
    stage: 'mature',
    stage_th: 'Harvest Ready · พร้อมเก็บเกี่ยว',
    stage_color: '#C0622F',
    density: 65,
    tree_count: 341,
    grades: { A: 60, B: 28, C: 8, U: 4 },
    problems: { insect: 4, disease: 2, weed: 1 },
    harvest: 'ready',
    health_score: 0.92,
    svg_rect: { x: 302, y: 244, w: 254, h: 192 },
  },
];

export const AI_SUMMARY: AISummary = {
  generated_at: new Date().toISOString(),
  zone_id: null,
  overall_assessment:
    'สวนส้มสมชายอยู่ในสภาวะวิกฤติในแปลง 3 และมีความเสี่ยงสูงในแปลง 2 จำเป็นต้องดำเนินการแก้ไขเร่งด่วนภายใน 24-48 ชั่วโมง เพื่อป้องกันโรคแคงเกอร์และ HLB แพร่ระบาดไปยังแปลง 1 และ 4 ซึ่งยังมีสุขภาพดี',
  key_findings: [
    'โรคแคงเกอร์ (Citrus Canker) ระบาดหนักในแปลง 3 ครอบคลุมพื้นที่ 38-41% ความเชื่อมั่น 92-94%',
    'เพลี้ยไก่แจ้ส้มพบในแปลง 3 ระดับวิกฤติ เป็นพาหะนำโรค HLB',
    'โรค HLB Greening พบในแปลง 2 ต้องเฝ้าระวังและกำจัดพาหะโดยด่วน',
    'วัชพืชใบกว้างพบในทุกแปลง แต่ระดับต่ำในแปลง 1',
    'แปลง 1 และ 4 ยังมีสุขภาพดี ควรป้องกันไม่ให้รับเชื้อจากแปลงอื่น',
  ],
  action_items: [
    {
      priority: 'high',
      action: 'ฉีดพ่นคอปเปอร์ออกซีคลอไรด์ในแปลง 3 ทันทีวันนี้',
      expected_outcome: 'ควบคุมโรคแคงเกอร์ภายใน 3-5 วัน ลดพื้นที่ติดโรค 60%',
    },
    {
      priority: 'high',
      action: 'ฉีดพ่นอิมิดาโคลพริดในแปลง 3 และ 2 เพื่อกำจัดเพลี้ยไก่แจ้พาหะ HLB',
      expected_outcome: 'ลดประชากรเพลี้ยไก่แจ้ลง 80% ภายใน 48 ชั่วโมง',
    },
    {
      priority: 'medium',
      action: 'ตัดกิ่งที่แสดงอาการแคงเกอร์ในแปลง 3 ออกและเผาทำลายทันที',
      expected_outcome: 'ลดแหล่งสะสมเชื้อ ป้องกันการแพร่กระจายในสวน',
    },
    {
      priority: 'low',
      action: 'กำจัดวัชพืชโคนต้นในแปลง 1 ก่อนที่จะขยายพื้นที่',
      expected_outcome: 'ลดการแข่งขันธาตุอาหาร เพิ่มผลผลิตส้ม 5-8%',
    },
  ],
  confidence: 0.87,
};
