import type {
  FarmSummary,
  Detection,
  MapData,
  Report,
  Task,
  AISummary,
  YieldSummary,
  DroneStatus,
  ScanRecord,
  FarmOption,
} from './types';

export const FARM_SUMMARY: FarmSummary = {
  farm_id: 'farm-001',
  farm_name: 'ไร่สมชาย',
  last_scan_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  overall_health_score: 0.63,
  health_trend: 'declining',
  total_area_rai: 24.5,
  active_alerts: 4,
  zones: [
    {
      zone_id: 'zone-a',
      zone_name: 'แปลง A – ข้าวหอมมะลิ',
      health_score: 0.87,
      status: 'healthy',
    },
    {
      zone_id: 'zone-b',
      zone_name: 'แปลง B – ข้าวเจ้า',
      health_score: 0.58,
      status: 'warning',
    },
    {
      zone_id: 'zone-c',
      zone_name: 'แปลง C – ข้าวหอมนิล',
      health_score: 0.31,
      status: 'critical',
    },
  ],
  top_recommendation:
    'แปลง C มีโรคไหม้ข้าวระบาดหนัก ควรฉีดพ่นสารเคมีป้องกันโรคภายใน 24 ชั่วโมง',
};

export const DETECTIONS: Detection[] = [
  {
    detection_id: 'det-001',
    detected_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'Rice Blast',
    confidence: 0.94,
    severity: 'critical',
    affected_area_pct: 38.5,
    zone_id: 'zone-c',
    zone_name: 'แปลง C – ข้าวหอมนิล',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.12, y: 0.18, width: 0.45, height: 0.52 },
    recommendation:
      'ฉีดพ่นสารไตรไซคลาโซล 20% WP อัตรา 20 กรัมต่อน้ำ 20 ลิตร ทันที และหยุดให้น้ำชั่วคราว',
  },
  {
    detection_id: 'det-002',
    detected_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Brown Planthopper',
    confidence: 0.88,
    severity: 'high',
    affected_area_pct: 22.1,
    zone_id: 'zone-c',
    zone_name: 'แปลง C – ข้าวหอมนิล',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.3, y: 0.4, width: 0.25, height: 0.3 },
    recommendation:
      'ฉีดพ่นสารบูโปรเฟซิน 25% SC อัตรา 30 มล.ต่อน้ำ 20 ลิตร เน้นบริเวณโคนต้นข้าว',
  },
  {
    detection_id: 'det-003',
    detected_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'Bacterial Leaf Blight',
    confidence: 0.79,
    severity: 'high',
    affected_area_pct: 17.3,
    zone_id: 'zone-b',
    zone_name: 'แปลง B – ข้าวเจ้า',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.05, y: 0.1, width: 0.6, height: 0.4 },
    recommendation:
      'ใช้สารคอปเปอร์ไฮดรอกไซด์ 77% WP อัตรา 30 กรัมต่อน้ำ 20 ลิตร ฉีดพ่นในช่วงเย็น',
  },
  {
    detection_id: 'det-004',
    detected_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Stem Borer',
    confidence: 0.85,
    severity: 'medium',
    affected_area_pct: 11.8,
    zone_id: 'zone-b',
    zone_name: 'แปลง B – ข้าวเจ้า',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.2, y: 0.25, width: 0.35, height: 0.45 },
    recommendation:
      'ใส่กับดักแสงไฟล่อแมลง และฉีดพ่นคาร์โบฟูราน 3% G อัตรา 3 กรัมต่อตารางเมตร',
  },
  {
    detection_id: 'det-005',
    detected_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.97,
    severity: 'medium',
    affected_area_pct: 9.4,
    zone_id: 'zone-a',
    zone_name: 'แปลง A – ข้าวหอมมะลิ',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.4, y: 0.5, width: 0.3, height: 0.3 },
    recommendation:
      'กำจัดวัชพืชด้วยสารบิสไพริแบค 10% SC อัตรา 20 มล.ต่อน้ำ 20 ลิตร ในช่วงอายุ 15-30 วัน',
  },
  {
    detection_id: 'det-006',
    detected_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'Rice Blast',
    confidence: 0.72,
    severity: 'medium',
    affected_area_pct: 8.2,
    zone_id: 'zone-b',
    zone_name: 'แปลง B – ข้าวเจ้า',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.15, y: 0.2, width: 0.4, height: 0.35 },
    recommendation:
      'ติดตามอาการอย่างใกล้ชิด ฉีดพ่นป้องกันด้วยสารไตรฟลอกซีสโตรบิน 10% WG',
  },
  {
    detection_id: 'det-007',
    detected_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.91,
    severity: 'low',
    affected_area_pct: 4.7,
    zone_id: 'zone-c',
    zone_name: 'แปลง C – ข้าวหอมนิล',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.6, y: 0.6, width: 0.2, height: 0.25 },
    recommendation: 'กำจัดด้วยแรงงาน หรือรอจนกว่าจะรักษาโรคหลักก่อน',
  },
  {
    detection_id: 'det-008',
    detected_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Brown Planthopper',
    confidence: 0.61,
    severity: 'low',
    affected_area_pct: 3.1,
    zone_id: 'zone-a',
    zone_name: 'แปลง A – ข้าวหอมมะลิ',
    status: 'resolved',
    image_url: null,
    bounding_box: { x: 0.7, y: 0.3, width: 0.15, height: 0.2 },
    recommendation: 'ดำเนินการแก้ไขแล้ว ติดตามผลต่อไป',
  },
  {
    detection_id: 'det-009',
    detected_at: new Date(Date.now() - 60 * 60 * 1000 * 60).toISOString(),
    type: 'disease',
    label: 'Bacterial Leaf Blight',
    confidence: 0.83,
    severity: 'high',
    affected_area_pct: 19.6,
    zone_id: 'zone-c',
    zone_name: 'แปลง C – ข้าวหอมนิล',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.08, y: 0.35, width: 0.5, height: 0.4 },
    recommendation:
      'ฉีดพ่นสารฆ่าเชื้อแบคทีเรียและลดการให้น้ำเพื่อป้องกันการแพร่กระจาย',
  },
  {
    detection_id: 'det-010',
    detected_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.76,
    severity: 'medium',
    affected_area_pct: 12.3,
    zone_id: 'zone-b',
    zone_name: 'แปลง B – ข้าวเจ้า',
    status: 'resolved',
    image_url: null,
    bounding_box: { x: 0.25, y: 0.55, width: 0.35, height: 0.28 },
    recommendation: 'ดำเนินการกำจัดวัชพืชแล้ว',
  },
  {
    detection_id: 'det-011',
    detected_at: new Date(Date.now() - 80 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Stem Borer',
    confidence: 0.69,
    severity: 'low',
    affected_area_pct: 5.8,
    zone_id: 'zone-a',
    zone_name: 'แปลง A – ข้าวหอมมะลิ',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.5, y: 0.2, width: 0.22, height: 0.3 },
    recommendation: 'ติดตามอาการ ถ้าพบเพิ่มให้ดำเนินการฉีดพ่นทันที',
  },
  {
    detection_id: 'det-012',
    detected_at: new Date(Date.now() - 90 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'Rice Blast',
    confidence: 0.92,
    severity: 'critical',
    affected_area_pct: 41.2,
    zone_id: 'zone-c',
    zone_name: 'แปลง C – ข้าวหอมนิล',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.1, y: 0.1, width: 0.55, height: 0.6 },
    recommendation:
      'เร่งด่วน: ฉีดพ่นสารไตรไซคลาโซลและแยกแปลงนี้ออกจากแปลงอื่น',
  },
  {
    detection_id: 'det-013',
    detected_at: new Date(Date.now() - 100 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.88,
    severity: 'low',
    affected_area_pct: 6.1,
    zone_id: 'zone-a',
    zone_name: 'แปลง A – ข้าวหอมมะลิ',
    status: 'resolved',
    image_url: null,
    bounding_box: { x: 0.45, y: 0.45, width: 0.28, height: 0.32 },
    recommendation: 'กำจัดวัชพืชแล้ว',
  },
  {
    detection_id: 'det-014',
    detected_at: new Date(Date.now() - 110 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Brown Planthopper',
    confidence: 0.75,
    severity: 'medium',
    affected_area_pct: 14.4,
    zone_id: 'zone-b',
    zone_name: 'แปลง B – ข้าวเจ้า',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.18, y: 0.3, width: 0.4, height: 0.38 },
    recommendation:
      'ฉีดพ่นสารบูโปรเฟซิน ผสมกับน้ำสะอาด ฉีดในเวลาเช้าตรู่',
  },
  {
    detection_id: 'det-015',
    detected_at: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'Bacterial Leaf Blight',
    confidence: 0.66,
    severity: 'medium',
    affected_area_pct: 10.7,
    zone_id: 'zone-a',
    zone_name: 'แปลง A – ข้าวหอมมะลิ',
    status: 'resolved',
    image_url: null,
    bounding_box: { x: 0.32, y: 0.15, width: 0.38, height: 0.42 },
    recommendation: 'ดำเนินการรักษาแล้ว อาการดีขึ้น',
  },
  {
    detection_id: 'det-016',
    detected_at: new Date(Date.now() - 130 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Stem Borer',
    confidence: 0.82,
    severity: 'high',
    affected_area_pct: 25.9,
    zone_id: 'zone-c',
    zone_name: 'แปลง C – ข้าวหอมนิล',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.22, y: 0.28, width: 0.48, height: 0.5 },
    recommendation: 'ฉีดพ่นสารคาร์โบฟูรานและติดกับดักฟีโรโมน',
  },
  {
    detection_id: 'det-017',
    detected_at: new Date(Date.now() - 140 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.93,
    severity: 'low',
    affected_area_pct: 3.9,
    zone_id: 'zone-b',
    zone_name: 'แปลง B – ข้าวเจ้า',
    status: 'resolved',
    image_url: null,
    bounding_box: { x: 0.55, y: 0.58, width: 0.2, height: 0.22 },
    recommendation: 'กำจัดด้วยแรงงานแล้ว',
  },
  {
    detection_id: 'det-018',
    detected_at: new Date(Date.now() - 150 * 60 * 60 * 1000).toISOString(),
    type: 'disease',
    label: 'Rice Blast',
    confidence: 0.78,
    severity: 'high',
    affected_area_pct: 20.5,
    zone_id: 'zone-b',
    zone_name: 'แปลง B – ข้าวเจ้า',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.1, y: 0.12, width: 0.5, height: 0.48 },
    recommendation:
      'ฉีดพ่นสารป้องกันโรคและเพิ่มความระมัดระวังในการให้น้ำ',
  },
  {
    detection_id: 'det-019',
    detected_at: new Date(Date.now() - 160 * 60 * 60 * 1000).toISOString(),
    type: 'pest',
    label: 'Brown Planthopper',
    confidence: 0.84,
    severity: 'critical',
    affected_area_pct: 35.6,
    zone_id: 'zone-c',
    zone_name: 'แปลง C – ข้าวหอมนิล',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.05, y: 0.05, width: 0.6, height: 0.65 },
    recommendation:
      'เร่งด่วน: ระบาดหนักมาก ควรปล่อยน้ำเข้าแปลงและฉีดพ่นสารทันที',
  },
  {
    detection_id: 'det-020',
    detected_at: new Date(Date.now() - 170 * 60 * 60 * 1000).toISOString(),
    type: 'weed',
    label: 'Broadleaf Weeds',
    confidence: 0.71,
    severity: 'medium',
    affected_area_pct: 13.8,
    zone_id: 'zone-a',
    zone_name: 'แปลง A – ข้าวหอมมะลิ',
    status: 'active',
    image_url: null,
    bounding_box: { x: 0.35, y: 0.4, width: 0.35, height: 0.35 },
    recommendation:
      'ฉีดพ่นสารกำจัดวัชพืชในช่วงเช้า ก่อนแสงแดดแรง',
  },
];

export const MAP_DATA: MapData = {
  farm_id: 'farm-001',
  center_lat: 18.7617,
  center_lng: 98.9667,
  zoom_default: 15,
  zones: [
    {
      zone_id: 'zone-a',
      zone_name: 'แปลง A – ข้าวหอมมะลิ',
      health_score: 0.87,
      status: 'healthy',
      polygon: [
        { lat: 18.7635, lng: 98.9645 },
        { lat: 18.7635, lng: 98.9680 },
        { lat: 18.7617, lng: 98.9680 },
        { lat: 18.7617, lng: 98.9645 },
      ],
      detection_count: 5,
    },
    {
      zone_id: 'zone-b',
      zone_name: 'แปลง B – ข้าวเจ้า',
      health_score: 0.58,
      status: 'warning',
      polygon: [
        { lat: 18.7617, lng: 98.9645 },
        { lat: 18.7617, lng: 98.9680 },
        { lat: 18.7600, lng: 98.9680 },
        { lat: 18.7600, lng: 98.9645 },
      ],
      detection_count: 7,
    },
    {
      zone_id: 'zone-c',
      zone_name: 'แปลง C – ข้าวหอมนิล',
      health_score: 0.31,
      status: 'critical',
      polygon: [
        { lat: 18.7617, lng: 98.9680 },
        { lat: 18.7617, lng: 98.9710 },
        { lat: 18.7600, lng: 98.9710 },
        { lat: 18.7600, lng: 98.9680 },
      ],
      detection_count: 8,
    },
  ],
  detection_markers: [
    { detection_id: 'det-001', lat: 18.7605, lng: 98.9690, type: 'disease', severity: 'critical' },
    { detection_id: 'det-002', lat: 18.7608, lng: 98.9695, type: 'pest', severity: 'high' },
    { detection_id: 'det-003', lat: 18.7610, lng: 98.9660, type: 'disease', severity: 'high' },
    { detection_id: 'det-004', lat: 18.7612, lng: 98.9658, type: 'pest', severity: 'medium' },
    { detection_id: 'det-005', lat: 18.7625, lng: 98.9662, type: 'weed', severity: 'medium' },
    { detection_id: 'det-006', lat: 18.7613, lng: 98.9655, type: 'disease', severity: 'medium' },
    { detection_id: 'det-007', lat: 18.7603, lng: 98.9698, type: 'weed', severity: 'low' },
    { detection_id: 'det-009', lat: 18.7602, lng: 98.9693, type: 'disease', severity: 'high' },
    { detection_id: 'det-012', lat: 18.7606, lng: 98.9700, type: 'disease', severity: 'critical' },
    { detection_id: 'det-014', lat: 18.7611, lng: 98.9665, type: 'pest', severity: 'medium' },
    { detection_id: 'det-016', lat: 18.7604, lng: 98.9697, type: 'pest', severity: 'high' },
    { detection_id: 'det-018', lat: 18.7609, lng: 98.9653, type: 'disease', severity: 'high' },
    { detection_id: 'det-019', lat: 18.7601, lng: 98.9702, type: 'pest', severity: 'critical' },
  ],
};

export const REPORTS: Record<'daily' | 'weekly' | 'monthly', Report> = {
  daily: {
    period: 'daily',
    generated_at: new Date().toISOString(),
    date_range: {
      from: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      to: new Date().toISOString().split('T')[0],
    },
    summary:
      'วันนี้ตรวจพบโรคไหม้ข้าวและเพลี้ยกระโดดสีน้ำตาลในแปลง C ระดับวิกฤติ ต้องดำเนินการแก้ไขด่วน คะแนนสุขภาพโดยรวมลดลง 0.08 จากเมื่อวาน',
    health_score_avg: 0.63,
    health_score_change: -0.08,
    total_detections: 7,
    detections_by_type: { disease: 3, weed: 1, pest: 3 },
    yield_estimate_kg: 4850,
    yield_confidence: 0.72,
    recommendations: [
      'ฉีดพ่นสารไตรไซคลาโซลในแปลง C ทันที',
      'ตรวจสอบระดับน้ำในแปลง B และ C',
      'ติดกับดักฟีโรโมนดักจับหนอนกอ',
    ],
    chart_data: [
      { label: '06:00', health_score: 0.71, detections: 1 },
      { label: '09:00', health_score: 0.68, detections: 2 },
      { label: '12:00', health_score: 0.65, detections: 3 },
      { label: '15:00', health_score: 0.63, detections: 5 },
      { label: '18:00', health_score: 0.63, detections: 7 },
    ],
  },
  weekly: {
    period: 'weekly',
    generated_at: new Date().toISOString(),
    date_range: {
      from: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      to: new Date().toISOString().split('T')[0],
    },
    summary:
      'สัปดาห์นี้ตรวจพบปัญหาเพิ่มขึ้น 35% จากสัปดาห์ที่แล้ว โรคไหม้ข้าวแพร่ระบาดหนักในแปลง C ส่งผลให้คะแนนสุขภาพโดยรวมลดลงต่อเนื่อง',
    health_score_avg: 0.67,
    health_score_change: -0.15,
    total_detections: 20,
    detections_by_type: { disease: 9, weed: 6, pest: 5 },
    yield_estimate_kg: 18200,
    yield_confidence: 0.68,
    recommendations: [
      'วางแผนจัดการโรคอย่างเป็นระบบทั้งฟาร์ม',
      'พิจารณาเพิ่มความถี่การสแกนโดรนเป็น 2 ครั้งต่อวัน',
      'ปรึกษาเกษตรกรในพื้นที่เกี่ยวกับโรคระบาด',
      'ตรวจดินและปรับสมดุลธาตุอาหาร',
    ],
    chart_data: [
      { label: 'จ.', health_score: 0.82, detections: 1 },
      { label: 'อ.', health_score: 0.79, detections: 2 },
      { label: 'พ.', health_score: 0.75, detections: 4 },
      { label: 'พฤ.', health_score: 0.71, detections: 5 },
      { label: 'ศ.', health_score: 0.68, detections: 6 },
      { label: 'ส.', health_score: 0.65, detections: 8 },
      { label: 'อา.', health_score: 0.63, detections: 7 },
    ],
  },
  monthly: {
    period: 'monthly',
    generated_at: new Date().toISOString(),
    date_range: {
      from: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      to: new Date().toISOString().split('T')[0],
    },
    summary:
      'เดือนนี้คะแนนสุขภาพฟาร์มโดยรวมลดลงจาก 0.85 เหลือ 0.63 โรคไหม้ข้าวและเพลี้ยกระโดดสีน้ำตาลเป็นปัญหาหลัก ผลผลิตคาดการณ์ต่ำกว่าเป้า 12%',
    health_score_avg: 0.74,
    health_score_change: -0.22,
    total_detections: 48,
    detections_by_type: { disease: 21, weed: 14, pest: 13 },
    yield_estimate_kg: 72400,
    yield_confidence: 0.61,
    recommendations: [
      'วางแผนป้องกันโรคก่อนฤดูกาลเพาะปลูกครั้งหน้า',
      'ลงทุนในระบบให้น้ำที่แม่นยำเพื่อลดความเสี่ยง',
      'ฝึกอบรมพนักงานเรื่องการจัดการโรคพืช',
      'พิจารณาปลูกพันธุ์ต้านทานโรคในฤดูหน้า',
      'สร้างแนวกั้นระหว่างแปลงเพื่อป้องกันการแพร่กระจาย',
    ],
    chart_data: [
      { label: 'สัปดาห์ 1', health_score: 0.85, detections: 4 },
      { label: 'สัปดาห์ 2', health_score: 0.80, detections: 8 },
      { label: 'สัปดาห์ 3', health_score: 0.74, detections: 14 },
      { label: 'สัปดาห์ 4', health_score: 0.63, detections: 22 },
    ],
  },
};

export const TASKS: Task[] = [
  {
    task_id: 'task-001',
    title: 'ฉีดพ่นสารไตรไซคลาโซลในแปลง C',
    description: 'ใช้ไตรไซคลาโซล 20% WP อัตรา 20 กรัมต่อน้ำ 20 ลิตร ครอบคลุมพื้นที่ทั้งหมด',
    priority: 'high',
    status: 'pending',
    due_date: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-c',
    related_detection_id: 'det-001',
  },
  {
    task_id: 'task-002',
    title: 'ติดกับดักฟีโรโมนแมลง',
    description: 'ติดตั้งกับดักฟีโรโมนดักจับหนอนกอในแปลง B และ C อย่างน้อย 5 จุดต่อแปลง',
    priority: 'high',
    status: 'in_progress',
    due_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-b',
    related_detection_id: 'det-004',
  },
  {
    task_id: 'task-003',
    title: 'ตรวจสอบระดับน้ำในแปลงทั้งหมด',
    description: 'วัดระดับน้ำและปรับให้เหมาะสม ไม่ควรเกิน 5 ซม. เพื่อลดความชื้น',
    priority: 'medium',
    status: 'pending',
    due_date: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: null,
    related_detection_id: null,
  },
  {
    task_id: 'task-004',
    title: 'กำจัดวัชพืชในแปลง A',
    description: 'ฉีดพ่นบิสไพริแบค 10% SC หรือจ้างแรงงานกำจัดด้วยมือ',
    priority: 'medium',
    status: 'pending',
    due_date: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-a',
    related_detection_id: 'det-005',
  },
  {
    task_id: 'task-005',
    title: 'บินโดรนสแกนซ้ำแปลง C',
    description: 'สแกนซ้ำหลังจากฉีดพ่นสารเคมีเพื่อประเมินผล',
    priority: 'high',
    status: 'pending',
    due_date: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-c',
    related_detection_id: null,
  },
  {
    task_id: 'task-006',
    title: 'ซื้อสารเคมีเพิ่มเติม',
    description: 'สั่งซื้อไตรไซคลาโซล, บูโปรเฟซิน, และสารบิสไพริแบค',
    priority: 'medium',
    status: 'in_progress',
    due_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: null,
    related_detection_id: null,
  },
  {
    task_id: 'task-007',
    title: 'รายงานผลให้เกษตรอำเภอ',
    description: 'แจ้งเจ้าหน้าที่เกษตรอำเภอเรื่องโรคระบาดในไร่เพื่อขอคำแนะนำ',
    priority: 'low',
    status: 'pending',
    due_date: new Date(Date.now() + 96 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: null,
    related_detection_id: null,
  },
  {
    task_id: 'task-008',
    title: 'ปรับระบบชลประทาน',
    description: 'ติดตั้งระบบให้น้ำแบบหยดในแปลง B เพื่อลดความชื้นส่วนเกิน',
    priority: 'low',
    status: 'done',
    due_date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-b',
    related_detection_id: null,
  },
  {
    task_id: 'task-009',
    title: 'ฉีดพ่นสารบูโปรเฟซิน',
    description: 'ฉีดพ่นบูโปรเฟซิน 25% SC ครอบคลุมแปลง C บริเวณโคนต้น',
    priority: 'high',
    status: 'pending',
    due_date: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString().split('T')[0],
    zone_id: 'zone-c',
    related_detection_id: 'det-002',
  },
  {
    task_id: 'task-010',
    title: 'บันทึกข้อมูลสภาพอากาศ',
    description: 'จดบันทึกอุณหภูมิ ความชื้น และปริมาณน้ำฝนประจำวัน',
    priority: 'low',
    status: 'done',
    due_date: new Date().toISOString().split('T')[0],
    zone_id: null,
    related_detection_id: null,
  },
];

export const YIELD_SUMMARY: YieldSummary = {
  estimated_kg: 9250,
  quality_grade: 'B',
  harvest_readiness_pct: 72,
  confidence: 0.78,
  zone_yields: [
    { zone_id: 'zone-a', zone_name: 'แปลง A – ข้าวหอมมะลิ', yield_level: 'high', estimated_kg: 4800 },
    { zone_id: 'zone-b', zone_name: 'แปลง B – ข้าวเจ้า', yield_level: 'medium', estimated_kg: 3200 },
    { zone_id: 'zone-c', zone_name: 'แปลง C – ข้าวหอมนิล', yield_level: 'low', estimated_kg: 1250 },
  ],
  plant_count: 12450,
  trend_pct: 12,
  days_since_planting: 87,
  estimated_harvest_date: '2026-06-15',
  growth_stage: 'near_harvest',
  grade_breakdown: { A: 38, B: 41, C: 16, damaged: 5 },
  trend_data: [
    { label: '7 วัน', kg: 8100 },
    { label: '6 วัน', kg: 8350 },
    { label: '5 วัน', kg: 8290 },
    { label: '4 วัน', kg: 8600 },
    { label: '3 วัน', kg: 8820 },
    { label: '2 วัน', kg: 9100 },
    { label: 'วันนี้', kg: 9250 },
  ],
  market_value_thb: 166500,
  ai_insights: [
    'แปลง B มีการเติบโตช้ากว่าปกติ ควรเพิ่มปุ๋ยไนโตรเจนเพื่อกระตุ้นการเติบโต',
    'ความเสี่ยงขาดน้ำเพิ่มขึ้นในแปลง C ควรเพิ่มความถี่การให้น้ำ',
    'คาดการณ์เก็บเกี่ยวภายใน 29 วัน เตรียมความพร้อมอุปกรณ์',
    'แนะนำใส่ปุ๋ยโพแทสเซียมสูตร 0-0-60 เพื่อเพิ่มคุณภาพและน้ำหนักเมล็ด',
  ],
};

export const DRONE_STATUS: DroneStatus = {
  mission_id: 'mission-042',
  status: 'uploading',
  completed_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  coverage_pct: 94,
  battery_pct: 68,
  signal_strength: 'strong',
  upload_pct: 67,
  last_scan_area_rai: 23.1,
};

export const FARM_LIST: FarmOption[] = [
  {
    farm_id: 'farm-001',
    farm_name: 'ไร่สมชาย',
    total_area_rai: 24.5,
    zones: [
      { zone_id: 'zone-a', zone_name: 'แปลง A', area_rai: 10.5, crop: 'ข้าวหอมมะลิ' },
      { zone_id: 'zone-b', zone_name: 'แปลง B', area_rai: 8.0, crop: 'ข้าวเจ้า' },
      { zone_id: 'zone-c', zone_name: 'แปลง C', area_rai: 6.0, crop: 'ข้าวหอมนิล' },
    ],
  },
  {
    farm_id: 'farm-002',
    farm_name: 'ไร่สมหมาย',
    total_area_rai: 18.0,
    zones: [
      { zone_id: 'zone-d', zone_name: 'แปลง A', area_rai: 10.0, crop: 'ข้าวหอมมะลิ' },
      { zone_id: 'zone-e', zone_name: 'แปลง B', area_rai: 8.0, crop: 'ข้าวหอมปทุม' },
    ],
  },
  {
    farm_id: 'farm-003',
    farm_name: 'ไร่บุญมาก',
    total_area_rai: 32.0,
    zones: [
      { zone_id: 'zone-f', zone_name: 'แปลง A', area_rai: 8.0, crop: 'ข้าวเจ้า' },
      { zone_id: 'zone-g', zone_name: 'แปลง B', area_rai: 9.0, crop: 'ข้าวเหนียว' },
      { zone_id: 'zone-h', zone_name: 'แปลง C', area_rai: 8.0, crop: 'ข้าวหอมมะลิ' },
      { zone_id: 'zone-i', zone_name: 'แปลง D', area_rai: 7.0, crop: 'ข้าวสินเหล็ก' },
    ],
  },
];

export const SCAN_HISTORY: ScanRecord[] = [
  { scan_id: 'scan-001', scanned_at: new Date().toISOString(), label: 'ผลล่าสุด' },
  {
    scan_id: 'scan-002',
    scanned_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    label: 'เมื่อวาน',
  },
  {
    scan_id: 'scan-003',
    scanned_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    label: '3 วันที่แล้ว',
  },
  {
    scan_id: 'scan-004',
    scanned_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    label: '7 วันที่แล้ว',
  },
];

export const AI_SUMMARY: AISummary = {
  generated_at: new Date().toISOString(),
  zone_id: null,
  overall_assessment:
    'ฟาร์มไร่สมชายอยู่ในสภาวะวิกฤติในแปลง C และมีความเสี่ยงสูงในแปลง B จำเป็นต้องดำเนินการแก้ไขเร่งด่วนภายใน 24-48 ชั่วโมง เพื่อป้องกันการแพร่ระบาดไปยังแปลง A ซึ่งยังมีสุขภาพดี',
  key_findings: [
    'โรคไหม้ข้าว (Rice Blast) ระบาดหนักในแปลง C ครอบคลุมพื้นที่ 38-41% ความเชื่อมั่น 92-94%',
    'เพลี้ยกระโดดสีน้ำตาลพบในแปลง C ระดับวิกฤติ ประชากรเพิ่มขึ้นเร็ว',
    'โรคขอบใบไหม้แบคทีเรียพบในแปลง B และ C ต้องเฝ้าระวัง',
    'วัชพืชใบกว้างพบในทุกแปลง แต่ระดับต่ำในแปลง A',
    'แปลง A ยังมีสุขภาพดี ควรป้องกันไม่ให้รับเชื้อจากแปลงอื่น',
  ],
  action_items: [
    {
      priority: 'high',
      action: 'ฉีดพ่นสารไตรไซคลาโซลในแปลง C ทันทีวันนี้',
      expected_outcome: 'ควบคุมโรคไหม้ข้าวภายใน 3-5 วัน ลดพื้นที่ติดโรค 60%',
    },
    {
      priority: 'high',
      action: 'ฉีดพ่นสารบูโปรเฟซินในแปลง C และ B เพื่อกำจัดเพลี้ยกระโดด',
      expected_outcome: 'ลดประชากรเพลี้ยลง 80% ภายใน 48 ชั่วโมง',
    },
    {
      priority: 'medium',
      action: 'ปรับระดับน้ำในแปลง C ให้ต่ำลง 2-3 ซม. เพื่อลดความชื้น',
      expected_outcome: 'ลดสภาพแวดล้อมที่เหมาะกับการแพร่โรค',
    },
    {
      priority: 'low',
      action: 'กำจัดวัชพืชในแปลง A ก่อนที่จะขยายพื้นที่',
      expected_outcome: 'ลดการแข่งขันธาตุอาหาร เพิ่มผลผลิต 5-8%',
    },
  ],
  confidence: 0.87,
};
